version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile  
    container_name: rs_challenge_php_app
    volumes:
      - .:/app 
    working_dir: /app
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t /app/public
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: rs_challenge_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
